### ISSUE TITLE
Files to remove

### ISSUE THREAD

**Issue by tylerm390** [UCF-Apocalypse-Attack/hackpack#23]
- [x] Segment Tree
- [x]  Lazy Segment Tree
- [x]  Union-Find (Can we rename rollback to DSU)
- [x]  Sub-Matrix
- [x]  Matrix
- [x]  Point
- [x]  Polygon Area
- [x]  In-Hull (Hull-Tangents Handles that)
- [x]  Point3D (but add in some of the niche things like rotate around axis)
- [x]  Polyhedron
- [x]  Bellman Ford
- [x]  Floyd-Warshall
- [x]  Top-Sort
- [x]  Push-Relabel? (Update Gomory Hu)
- [x]  Edmonds-Karp (Maybe add Capcity Scalling FFA for a shorter flow alternative)
- [x]  Min-Cut
- [ ]  DFS Matching
- [ ] MVC
- [x] Integrate and Integrate Adaptive (Rename IntegrateAdaptiveTyler to IntegrateAdaptive)
- [x] Modular Arithmetic
- [x] ModPow
- [x] Remove one of the Aho-Corasicks
- [x] Ternary Search

**Comment by ssk4988** [comment]
@tylerm390 we no longer have any Point3D stuff in here including the angle and rotation stuff
